### ISSUE TITLE
 INFOGRAFIA REALIDAD AUMENTADA_Nancy Velasco Santiago

### ISSUE THREAD

**Issue by Nancy2050** [SistemasTecTlaxiaco/infografia-Nancy2050#1]
[INFOGRAFIA REALIDAD AUMENTADA_Nancy Velasco Santiago.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Nancy2050/files/8052849/INFOGRAFIA.REALIDAD.AUMENTADA_Nancy.Velasco.Santiago.pdf)

**Comment by EMMANUELRHZ** [comment]
Calificación=20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
