### ISSUE TITLE
INFOGRAFIA "INGENIERÍA DE REQUISITOS"

### ISSUE THREAD

**Issue by Nancy2050** [SistemasTecTlaxiaco/infografia-Nancy2050#2]
![Imagen1](https://user-images.githubusercontent.com/64548201/109736504-0b497980-7b8a-11eb-9352-f03754ac8dcf.png)

**Comment by 10154** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
